In [1]:
import numpy as np

In [2]:
np.array([2,3,7]) * 4 + 2 * np.array([5,3,9])

array([18, 18, 46])

In [3]:
np.array([2,1]) * 4 + 3 * np.array([4,6])

array([20, 22])

In [4]:
v = np.array([2,1])
w = np.array([-2,1])
v.dot(w)

-3

In [5]:
np.array([
            [2,1], 
            [4,6]
        ])

array([[2, 1],
       [4, 6]])

In [6]:
X = _

In [7]:
X

array([[2, 1],
       [4, 6]])

In [8]:
X[0,0]

2

In [9]:
X[0,:]

array([2, 1])

In [10]:
X[:,0]

array([2, 4])